dist: xenial

addons:
  snaps:
    - hugo --channel=extended
    - node --classic --channel=10

script:
  - git checkout origin/color1 -f
  - npm install
  - hugo
  - cp CNAME public/color1/.
  - git checkout origin/color2 -f
  - npm install
  - hugo
  - cp CNAME public/color2/.
  - git checkout origin/color3 -f
  - npm install
  - hugo
  - cp CNAME public/color3/.
  - git checkout origin/master
  - npm install
  - hugo
  - cp CNAME public/.
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local_dir: public
  on:
    branch: master
