dist: xenial

addons:
  snaps:
    - hugo --channel=extended
    - node --classic --channel=10

script:
  - npm install
  - npm render-presentations
  - hugo
  - cp CNAME public/.
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local_dir: public
  on:
    branch: master
