backend:
  name: github
  repo: mib-unibe/unihack
  branch: master
  squash_merges: true
media_folder: "static"
publish_mode: editorial_workflow
display_url: https://www.unihack.ch
collections:
  - name: "challenges"
    label: "Challenges"
    label_singular: "Challenge"
    description: "These are the available challenges for the hackathon."
    folder: "content/challenges"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Level",
          name: "levels",
          widget: "select",
          multiple: true,
          options: ["Beginner", "Intermediate", "Advanced"],
          required: true,
        }
      - { label: "Hardware", name: "hardware", widget: "list", allow_add: true }
